//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace NAA.WsAccess.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [SpecialSetting(SpecialSetting.WebServiceUrl)]
        [DefaultSettingValue("http://webteach_net.hallam.shu.ac.uk/cmsmr2/SheffieldWebService.asmx")]
        public string NAA_WsAccess_uk_ac_shu_hallam_webteach_net_SheffieldWebService {
            get {
                return ((string)(this["NAA_WsAccess_uk_ac_shu_hallam_webteach_net_SheffieldWebService"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [SpecialSetting(SpecialSetting.WebServiceUrl)]
        [DefaultSettingValue("http://webteach_net.hallam.shu.ac.uk/cmsmr2/SHUWebService.asmx")]
        public string NAA_WsAccess_uk_ac_shu_hallam_webteach_net1_SHUWebService {
            get {
                return ((string)(this["NAA_WsAccess_uk_ac_shu_hallam_webteach_net1_SHUWebService"]));
            }
        }
    }
}
