//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Threading;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using NAA.WsAccess.Properties;

#pragma warning disable 1591

namespace NAA.WsAccess.uk.ac.shu.hallam.webteach_net1 {
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name="SHUWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SHUWebService : SoapHttpClientProtocol {
        
        private SendOrPostCallback SHUCoursesOperationCompleted;
        
        private SendOrPostCallback SHUCoursesInShortOperationCompleted;
        
        private SendOrPostCallback HelloWorldOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SHUWebService() {
            this.Url = Settings.Default.NAA_WsAccess_uk_ac_shu_hallam_webteach_net1_SHUWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SHUCoursesCompletedEventHandler SHUCoursesCompleted;
        
        /// <remarks/>
        public event SHUCoursesInShortCompletedEventHandler SHUCoursesInShortCompleted;
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/SHUCourses", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public SHUCourse[] SHUCourses() {
            object[] results = this.Invoke("SHUCourses", new object[0]);
            return ((SHUCourse[])(results[0]));
        }
        
        /// <remarks/>
        public void SHUCoursesAsync() {
            this.SHUCoursesAsync(null);
        }
        
        /// <remarks/>
        public void SHUCoursesAsync(object userState) {
            if ((this.SHUCoursesOperationCompleted == null)) {
                this.SHUCoursesOperationCompleted = new SendOrPostCallback(this.OnSHUCoursesOperationCompleted);
            }
            this.InvokeAsync("SHUCourses", new object[0], this.SHUCoursesOperationCompleted, userState);
        }
        
        private void OnSHUCoursesOperationCompleted(object arg) {
            if ((this.SHUCoursesCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.SHUCoursesCompleted(this, new SHUCoursesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/SHUCoursesInShort", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public SHUCourseShort[] SHUCoursesInShort() {
            object[] results = this.Invoke("SHUCoursesInShort", new object[0]);
            return ((SHUCourseShort[])(results[0]));
        }
        
        /// <remarks/>
        public void SHUCoursesInShortAsync() {
            this.SHUCoursesInShortAsync(null);
        }
        
        /// <remarks/>
        public void SHUCoursesInShortAsync(object userState) {
            if ((this.SHUCoursesInShortOperationCompleted == null)) {
                this.SHUCoursesInShortOperationCompleted = new SendOrPostCallback(this.OnSHUCoursesInShortOperationCompleted);
            }
            this.InvokeAsync("SHUCoursesInShort", new object[0], this.SHUCoursesInShortOperationCompleted, userState);
        }
        
        private void OnSHUCoursesInShortOperationCompleted(object arg) {
            if ((this.SHUCoursesInShortCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.SHUCoursesInShortCompleted(this, new SHUCoursesInShortCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=SoapBindingUse.Literal, ParameterStyle=SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            Uri wsUri = new Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.7.2612.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://tempuri.org/")]
    public partial class SHUCourse {
        
        private int courseIdField;
        
        private string cNameField;
        
        private string cRequirementsField;
        
        private string cDescriptionField;
        
        private string cDegreeField;
        
        private string cTarifField;
        
        private string cNSSField;
        
        /// <remarks/>
        public int CourseId {
            get {
                return this.courseIdField;
            }
            set {
                this.courseIdField = value;
            }
        }
        
        /// <remarks/>
        public string CName {
            get {
                return this.cNameField;
            }
            set {
                this.cNameField = value;
            }
        }
        
        /// <remarks/>
        public string CRequirements {
            get {
                return this.cRequirementsField;
            }
            set {
                this.cRequirementsField = value;
            }
        }
        
        /// <remarks/>
        public string CDescription {
            get {
                return this.cDescriptionField;
            }
            set {
                this.cDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string CDegree {
            get {
                return this.cDegreeField;
            }
            set {
                this.cDegreeField = value;
            }
        }
        
        /// <remarks/>
        public string CTarif {
            get {
                return this.cTarifField;
            }
            set {
                this.cTarifField = value;
            }
        }
        
        /// <remarks/>
        public string CNSS {
            get {
                return this.cNSSField;
            }
            set {
                this.cNSSField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.7.2612.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://tempuri.org/")]
    public partial class SHUCourseShort {
        
        private int courseIdField;
        
        private string cNameField;
        
        private string cRequirementsField;
        
        private string cDegreeField;
        
        private string cTarifField;
        
        /// <remarks/>
        public int CourseId {
            get {
                return this.courseIdField;
            }
            set {
                this.courseIdField = value;
            }
        }
        
        /// <remarks/>
        public string CName {
            get {
                return this.cNameField;
            }
            set {
                this.cNameField = value;
            }
        }
        
        /// <remarks/>
        public string CRequirements {
            get {
                return this.cRequirementsField;
            }
            set {
                this.cRequirementsField = value;
            }
        }
        
        /// <remarks/>
        public string CDegree {
            get {
                return this.cDegreeField;
            }
            set {
                this.cDegreeField = value;
            }
        }
        
        /// <remarks/>
        public string CTarif {
            get {
                return this.cTarifField;
            }
            set {
                this.cTarifField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.2556.0")]
    public delegate void SHUCoursesCompletedEventHandler(object sender, SHUCoursesCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class SHUCoursesCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SHUCoursesCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SHUCourse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SHUCourse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.2556.0")]
    public delegate void SHUCoursesInShortCompletedEventHandler(object sender, SHUCoursesInShortCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class SHUCoursesInShortCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SHUCoursesInShortCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SHUCourseShort[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SHUCourseShort[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.2556.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class HelloWorldCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591